# Generated by Django 4.1.5 on 2023-02-04 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_uid_alter_colorvariant_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6e43d40f-db32-4d2f-9939-d2b7cfe33d8a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6e43d40f-db32-4d2f-9939-d2b7cfe33d8a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='product.colorvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='product.sizevariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6e43d40f-db32-4d2f-9939-d2b7cfe33d8a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6e43d40f-db32-4d2f-9939-d2b7cfe33d8a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6e43d40f-db32-4d2f-9939-d2b7cfe33d8a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
