# Generated by Django 4.1.5 on 2023-02-05 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_cartitems_options_alter_cart_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('94e3b0c6-1418-4a33-8c12-d401ea1ac4b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('94e3b0c6-1418-4a33-8c12-d401ea1ac4b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('94e3b0c6-1418-4a33-8c12-d401ea1ac4b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('94e3b0c6-1418-4a33-8c12-d401ea1ac4b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('94e3b0c6-1418-4a33-8c12-d401ea1ac4b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('94e3b0c6-1418-4a33-8c12-d401ea1ac4b9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('94e3b0c6-1418-4a33-8c12-d401ea1ac4b9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
