# Generated by Django 4.1.5 on 2023-02-08 07:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_coupon_alter_cart_uid_alter_cartitems_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('2c2065b2-8f07-4dca-882d-82bdfdcf083a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
